package com.msproject.dataobject;

import java.util.Date;

public class PromoDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo.promo_id
     *
     * @mbg.generated Wed Mar 18 11:08:43 CST 2020
     */
    private Integer promoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo.item_id
     *
     * @mbg.generated Wed Mar 18 11:08:43 CST 2020
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo.promo_price
     *
     * @mbg.generated Wed Mar 18 11:08:43 CST 2020
     */
    private Double promoPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo.start_time
     *
     * @mbg.generated Wed Mar 18 11:08:43 CST 2020
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo.end_time
     *
     * @mbg.generated Wed Mar 18 11:08:43 CST 2020
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo.promo_name
     *
     * @mbg.generated Wed Mar 18 11:08:43 CST 2020
     */
    private String promoName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo.promo_id
     *
     * @return the value of promo.promo_id
     *
     * @mbg.generated Wed Mar 18 11:08:43 CST 2020
     */
    public Integer getPromoId() {
        return promoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo.promo_id
     *
     * @param promoId the value for promo.promo_id
     *
     * @mbg.generated Wed Mar 18 11:08:43 CST 2020
     */
    public void setPromoId(Integer promoId) {
        this.promoId = promoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo.item_id
     *
     * @return the value of promo.item_id
     *
     * @mbg.generated Wed Mar 18 11:08:43 CST 2020
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo.item_id
     *
     * @param itemId the value for promo.item_id
     *
     * @mbg.generated Wed Mar 18 11:08:43 CST 2020
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo.promo_price
     *
     * @return the value of promo.promo_price
     *
     * @mbg.generated Wed Mar 18 11:08:43 CST 2020
     */
    public Double getPromoPrice() {
        return promoPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo.promo_price
     *
     * @param promoPrice the value for promo.promo_price
     *
     * @mbg.generated Wed Mar 18 11:08:43 CST 2020
     */
    public void setPromoPrice(Double promoPrice) {
        this.promoPrice = promoPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo.start_time
     *
     * @return the value of promo.start_time
     *
     * @mbg.generated Wed Mar 18 11:08:43 CST 2020
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo.start_time
     *
     * @param startTime the value for promo.start_time
     *
     * @mbg.generated Wed Mar 18 11:08:43 CST 2020
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo.end_time
     *
     * @return the value of promo.end_time
     *
     * @mbg.generated Wed Mar 18 11:08:43 CST 2020
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo.end_time
     *
     * @param endTime the value for promo.end_time
     *
     * @mbg.generated Wed Mar 18 11:08:43 CST 2020
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo.promo_name
     *
     * @return the value of promo.promo_name
     *
     * @mbg.generated Wed Mar 18 11:08:43 CST 2020
     */
    public String getPromoName() {
        return promoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo.promo_name
     *
     * @param promoName the value for promo.promo_name
     *
     * @mbg.generated Wed Mar 18 11:08:43 CST 2020
     */
    public void setPromoName(String promoName) {
        this.promoName = promoName == null ? null : promoName.trim();
    }
}