package com.msproject.dataobject;

public class SequenceDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info.name
     *
     * @mbg.generated Tue Mar 17 11:44:21 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info.current_value
     *
     * @mbg.generated Tue Mar 17 11:44:21 CST 2020
     */
    private Integer currentValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info.step
     *
     * @mbg.generated Tue Mar 17 11:44:21 CST 2020
     */
    private Integer step;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info.max_value
     *
     * @mbg.generated Tue Mar 17 11:44:21 CST 2020
     */
    private Integer maxValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info.init_value
     *
     * @mbg.generated Tue Mar 17 11:44:21 CST 2020
     */
    private Integer initValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence_info.name
     *
     * @return the value of sequence_info.name
     *
     * @mbg.generated Tue Mar 17 11:44:21 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence_info.name
     *
     * @param name the value for sequence_info.name
     *
     * @mbg.generated Tue Mar 17 11:44:21 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence_info.current_value
     *
     * @return the value of sequence_info.current_value
     *
     * @mbg.generated Tue Mar 17 11:44:21 CST 2020
     */
    public Integer getCurrentValue() {
        return currentValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence_info.current_value
     *
     * @param currentValue the value for sequence_info.current_value
     *
     * @mbg.generated Tue Mar 17 11:44:21 CST 2020
     */
    public void setCurrentValue(Integer currentValue) {
        this.currentValue = currentValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence_info.step
     *
     * @return the value of sequence_info.step
     *
     * @mbg.generated Tue Mar 17 11:44:21 CST 2020
     */
    public Integer getStep() {
        return step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence_info.step
     *
     * @param step the value for sequence_info.step
     *
     * @mbg.generated Tue Mar 17 11:44:21 CST 2020
     */
    public void setStep(Integer step) {
        this.step = step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence_info.max_value
     *
     * @return the value of sequence_info.max_value
     *
     * @mbg.generated Tue Mar 17 11:44:21 CST 2020
     */
    public Integer getMaxValue() {
        return maxValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence_info.max_value
     *
     * @param maxValue the value for sequence_info.max_value
     *
     * @mbg.generated Tue Mar 17 11:44:21 CST 2020
     */
    public void setMaxValue(Integer maxValue) {
        this.maxValue = maxValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence_info.init_value
     *
     * @return the value of sequence_info.init_value
     *
     * @mbg.generated Tue Mar 17 11:44:21 CST 2020
     */
    public Integer getInitValue() {
        return initValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence_info.init_value
     *
     * @param initValue the value for sequence_info.init_value
     *
     * @mbg.generated Tue Mar 17 11:44:21 CST 2020
     */
    public void setInitValue(Integer initValue) {
        this.initValue = initValue;
    }
}